# Generated by Django 5.0.2 on 2024-02-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img_url',
            field=models.ImageField(default=None, null=True, upload_to='media/'),
        ),
    ]
