# Generated by Django 5.0.2 on 2024-03-26 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_customer_name_alter_product_img_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expenditure',
            fields=[
                ('expense_id', models.PositiveIntegerField(auto_created=True, primary_key=True, serialize=False, unique=True)),
                ('expense_type', models.CharField(max_length=20)),
                ('expense_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('expense_date', models.DateField()),
                ('voucher_no', models.CharField(max_length=20)),
                ('total_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('notes', models.TextField(max_length=50)),
            ],
        ),
    ]
