# Generated by Django 5.0.2 on 2024-03-26 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_expenditure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expenditure',
            name='expense_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
