# Generated by Django 5.0.2 on 2024-02-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_customer_invoice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='invoice',
            old_name='bought_on',
            new_name='generated_on',
        ),
    ]
